version: "3.7"

services:
  nginx:
    image: nginx:1.17.4-alpine
    #container_name: nginx_noc
    ports:
      - "8088:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:12.0-alpine
    #container_name: postgres_config
    volumes:
      - laravel_data:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      TZ: "Asia/Jakarta"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "docker"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped
    tty: true
    #container_name: php_config
    volumes:
      - ../app:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel

  scheduler:
    image: laravel-www
    # container_name: laravel-scheduler
    depends_on:
      - app
    volumes:
      - ../app:/var/www/html

networks:
  laravel:

volumes:
  laravel_data:
